export const SPACES_LOADING = 'SPACES_LOADING';
export const SPACES_FAILED = 'SPACES_FAILED';
export const ADD_SPACES = 'ADD_SPACES';

export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_FAILED = 'QUESTIONS_FAILED';
export const ADD_QUESTIONS = 'ADD_QUESTIONS';
