export const SPACES_LOADING = "SPACES_LOADING";
export const SPACES_FAILED = "SPACES_FAILED";
export const ADD_SPACES = "ADD_SPACES";

export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const QUESTIONS_FAILED = "QUESTIONS_FAILED";
export const ADD_QUESTIONS = "ADD_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const POST_FAIL = "POST_FAIL";
export const GET_USER_QUESTIONS= "GET_USER_QUESTIONS";
export const USER_QUESTIONS_LOADING= "USER_QUESTIONS_LOADING";
export const USER_QUESTIONS_FAILED = "USER_QUESTIONS_FAILED";


export const ANSWERS_LOADING = "ANSWERS_LOADING";
export const ANSWERS_FAILED = "ANSWERS_FAILED";
export const ADD_ANSWERS = "ADD_ANSWERS";
export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const GET_USER_ANSWERS="GET_USER_ANSWERS"
export const USER_ANSWERS_LOADING="USER_ANSWERS_LOADING"
export const USER_ANSWERS_FAILED="USER_ANSWERS_FAILED"

export const USER_LOADING = "USER_LOADING";
export const USER_FAILED = "USER_FAILED";
export const GET_USER = "GET_USER";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const ADD_QREACTION = 'ADD_QREACTION';
export const ADD_QREACTIONS = 'ADD_QREACTIONS';
export const QREACTIONS_FAILED = 'QREACTIONS_FAILED';
export const DELETE_QREACTION = 'DELETE_QREACTION';

export const ADD_AREACTION = 'ADD_AREACTION';
export const ADD_AREACTIONS = 'ADD_AREACTIONS';
export const AREACTIONS_FAILED = 'AREACTIONS_FAILED';
export const DELETE_AREACTION = 'DELETE_AREACTION';


export const BLOGS_LOADING = "BLOGS_LOADING";
export const BLOGS_FAILED = "BLOGS_FAILED";
export const ADD_BLOGS = "ADD_BLOGS";
export const ADD_BLOG = "ADD_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const GET_USER_BLOGS="GET_USER_BLOGS";
export const USER_BLOGS_FAILED="USER_BLOGS_FAILED"
export const USER_BLOGS_LOADING="USER_BLOGS_LOADING"


export const BLOGDEMANDS_LOADING = "BLOGDEMANDS_LOADING";
export const BLOGDEMANDS_FAILED = "BLOGDEMANDS_FAILED";
export const ADD_BLOGDEMANDS = "ADD_BLOGDEMANDS";
export const ADD_BLOGDEMAND = "ADD_BLOGDEMAND";
export const DELETE_BLOGDEMAND = "DELETE_BLOGDEMAND";
export const GET_USER_BLOG_DEMANDS = "GET_USER_BLOG_DEMANDS";
export const USER_BLOG_DEMANDS_FAILED = "USER_BLOG_DEMANDS_FAILED";
export const USER_BLOG_DEMAND_LOADING = "USER_BLOG_DEMAND_LOADING"

export const ADD_BREACTION = 'ADD_BREACTION';
export const ADD_BREACTIONS = 'ADD_BREACTIONS';
export const REACTIONS_BFAILED = 'REACTIONS_BFAILED';
export const DELETE_BREACTION = 'DELETE_BREACTION';

export const ADD_BCOMMENTS = "ADD_BCOMMENTS";
export const COMMENTS_BFAILED = "COMMENTS_BFAILED";
export const ADD_BCOMMENT = "ADD_BCOMMENT";
export const DELETE_BCOMMENT = "DELETE_BCOMMENT";


//Authentication
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const AUTH_FAILED = "AUTH_FAILED";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_FAILED = "UPDATE_FAILED";
export const CHANGE_FOLLOW = 'CHANGE_FOLLOW';
//Contact US form
export const CONTACT_US= "CONTACT_US";
export const FORM_FAILED = "FORM_FAILED";


