export const spaces = [
    {value:"Algorithms", label:'Algorithms'},
    {value:"Machine-Learning", label: "Machine Learning"},
    {value:"Data-Structures", label: "Data Structures"},
    {value:"Web-Development",label:'Web Development'}, 
    {value:"Android-Development", label:'Android Development'},
    {value:"Blockchain", label: 'Blockchain'},
    {value:'Ethical-Hacking', label: 'Ethical Hacking'},
    {value:'Operating-Systems', label: 'Operating Systems'},
    {value:'DBMS', label: 'DBMS'},
    {value:'Python', label: 'Python'},
    {value:"Programming-Language", label: "Programming Language"},
    // /{value:"C++", label:'C++'},
    {value:"Cloud-Computing", label:"Cloud Computing"},
    {value:"Computer-Architecture", label:"Computer Architecture"},
    {value:"Computer-Science-Others", label:"Computer Science Others"},
    {value:"Applied-Mathematics", label:"Applied Mathematics"},
    {value:"Applied-Science", label:"Applied Science"},
    {value:"Physical-Metallurgy-(MTN-102)",label:'Physical Metallurgy (MTN 102)'},
    {value:"Mechanical-Metallurgy-(MTN-303)",label:"Mechanical Metallurgy (MTN 303)"},
    {value:"corrosion-engineering(MTN-433)",label:"Corrosion Engineering (MTN 433)"},
    {value:"Extractive-Metallurgy-For-Nonferrous-Metals(MTN-201)",label:"Extractive Metallurgy For Nonferrous Metals (MTN 201)"},
    {value:"Steel-Making-(MTN-301)",label:"Steel Making (MTN 301)"},
    {value:"Ceramics-and-polymers-(MTN-210)",label:"Ceramics and polymers (MTN 210)"},
    {value:"Metal-casting-(MTN-208)",label:"Metal casting (MTN 208)"},
    {value:"Materials-Toining-Technology-(MTN-305)",label:"Materials Joining Technology (MTN 305)"},
    {value:"Heat-Treatment-(MTN-406)",label:"Heat Treatment (MTN 406)"},
    {value:"Solid-Mechanics(CEN-201)",label:"Solid Mechanics (CEN 201)"},
    {value:"Environmental-Engineering-(CEN-204)",label:"Environmental Engineering (CEN 204)"},
    {value:"Structural-Analysis-(CEN-207)",label:"Structural Analysis (CEN 207)"},
    {value:"Reinforced-Concrete-Design-(CEN-208)",label:"Reinforced Concrete Design (CEN 208)"},
    {value:"Geotechnical-Engineering-(CEN-210)",label:"Geotechnical Engineering (CEN 210)"},
    {value:"Transportation-Engineering-(CEN-203)",label:"Transportation Engineering (CEN 203)"},
    {value:"Design-Of-Steel-Structures-(CEN-301)",label:"Design Of Steel Structures (CEN 301)"},
    {value:"Structural-Analysis-(CEN-303)",label:"Structural Analysis (CEN 303)"},
    {value:"Fluid-Mechanics-(CEN-103)",label:"Fluid Mechanics (CEN 103)"},
    {value:"Building-Materials-Construction-And-Estimation-(CEN-102)",label:"Building Materials Construction And Estimation (CEN 102)"},
    {value:"Internal-Combustion-Engine-(MEN-425)",label:"Internal Combustion Engine (MEN 425)"},
    {value:"Production-And-Operation-Management-(MEN-401)",label:"Production And Operation Management (MEN 401)"},
    {value:"Applied-Thermodynamics-(MEN-209)",label:"Applied Thermodynamics (MEN 209)"},
    {value:"Automobile-Engineering-(MEN-417)",label:"Automobile Engineering (MEN 417)"},
    {value:"Computational-Fluid-Dynamics-For-Thermal-Stream-(MEMS-106)",label:"Computational Fluid Dynamics For Thermal Stream (MEMS 106)"},
    {value:"Dynamics-Of-Machine-(MEN-207)",label:"Dynamics Of Machine (MEN 207)"},
    {value:"Heat-Transfer-(MEMS-106)",label:"Heat Transfer (MEMS 106)"},
    {value:"Refrigration-And-Air-Conditioning-(MEN-210)",label:"Refrigration And Air Conditioning (MEN 210)"},
    {value:"Maintenance-Engineering-(MEN-402)",label:"Maintenance Engineering (MEN 402)"},
    {value:"Mechanical-Measurements-And-Metallurgy-(MEN-416)",label:"Mechanical Measurements And Metallurgy (MEN 416)"},
    {value:"CNC-Machines-And-Programming-(PEN-416)",label:"CNC Machines And Programming (PEN 416)"},
    {value:"Computer-Integrated-Manufacturing-(PEN-301)",label:"Computer Integrated Manufacturing (PEN 301)"},
    {value:"Design-Of-Machine-Elements-(PEN-208)",label:"Design Of Machine Elements (PEN 208)"},
    {value:"Engineering-Analysis-And-Design-(PEN-206)",label:"Engineering Analysis And Design (PEN 206)"},
    {value:"Industrial-Engineering-1-(PEN-210)",label:"Industrial Engineering 1 (PEN 210)"},
    {value:"Introduction-To-Industrial-And-Production-Engineering-(PEN-101)",label:"Introduction To Industrial And Production Engineering (PEN 101)"},
    {value:"Introduction-to-manufacturing-(PEN-102)",label:"Introduction To Manufacturing (PEN 102)"},
    {value:"Kinematic-And-Dynamics-(PEN-201)",label:"Kinematic And Dynamics (PEN 201)"},
    {value:"Machining-Technology-(PEN-211)",label:"Machining Technology (PEN 211)"},
    {value:"Tool-Designing-(PEN-209)",label:"Tool Designing (PEN 209)"},
    {value:"Digital-Design-(ECN 103)", label:'Digital Design-(ECN 103)'},
    {value:"Analog-Electronic-Circuits-I-(ECN-102)", label: 'Analog Electronic Circuits-I-(ECN-102)'},
    {value:"Analog-Electronic-Circuits-II-(ECN-102)", label: 'Analog Electronic Circuits-II-(ECN-102)'},
    {value:"Communication-Engineering-(ECN-201)", label:"Communication Engineering (ECN 201)"},
    {value:"Signal-and-Systems", label:"Signal and Systems"},
    {value:"VLSI-Design-(ECN-208)", label:"VLSI Design (ECN 208)"},
    {value:"Embedded-Systems-(ECN-305)", label:"Embedded Systems (ECN 305)"},
    {value:"Control-Systems-(ECN-401)", label:"Control Systems (ECN 401)"},
    {value:"HDL-based-system-Design-(ECN-411)", label:"HDL based system Design (ECN 411)"},
    {value:"Foundations-of-VLSI-CAD-(ECN-416)", label:"Foundations of VLSI CAD (ECN 416)"},
    {value:"Arduino", label:"Arduino"},
    {value:"IOT", label:"IOT"},
    {value:"Rasberry-Pi", label:"Rasberry Pi"},
    {value:"Robotics", label:"Robotics"},
    {value:"Electronics-and-Communication-Engineering-others", label:"Electronics and Communication Engineering others"},
    {value:"Analog-And-Digital-Electronics-(EEN-204)",label:"Analog And Digital Electronics (EEN 204)"},
    {value:"Control-Systems-(EEN-210)",label:"Control Systems (EEN 210)"},
    {value:"Electrical-Machines-(EEN-203)",label:"Electrical Machines (EEN 203)"},
    {value:"Electrical-Measurements-And-Instrumentation-(EEN-103)",label:"Electrical Measurements And Instrumentation (EEN 103)"},
    {value:"Electrical-Power-Systems-(EEN-202)",label:"Electrical Power Systems (EEN 202)"},
    {value:"High-Voltage-Engineering-(EEN-315)",label:"High Voltage Engineering (EEN 315)"},
    {value:"Power-Electronics-(EEN-207)",label:"Power Electronics (EEN 207)"},
    {value:"Introduction-To-Electrical-Engineering-(EEN-101)",label:"Introduction To Electrical Engineering (EEN 101)"},
    {value:"Microprocessors-And-Peripheral-Devices-(EEN-208)",label:"Microprocessors And Peripheral Devices (EEN 208)"},
    {value:"Networks-And-Systems(EEN-102)",label:"Networks And Systems (EEN 102)"},
    {value:"Production-Engineering-Others",label:"Production Engineering Others"},
    {value:"Electrical-Engineering-Others",label:"Electrical Engineering Others"},
    {value:"Metallurgy-Others",label:"Metallurgy Others"},
    {value:"Civil-Engineering-Others",label:"Civil Engineering Others"},
    {value:"Mechanical-Engineering-Others",label:"Mechanical Engineering Others"},
    {value:"Advanced-Aerodynamics-(AEN-421)",label:"Advanced Aerodynamics (AEN 421)"},
    {value:"Aero-Engine-Design-(AEN-207)",label:"Aero Engine Design (AEN 207)"},
    {value:"Aircraft-Propulsion-(AEN-202)",label:"Aircraft Propulsion (AEN 202)"},
    {value:"Aircraft-Systems-And-Instrumentation-(AEN-203)",label:"Aircraft Systems And Instrumentation (AEN 203)"},
    {value:"Airplane-Design-(AEN-303)",label:"Airplane Design (AEN 303)"},
    {value:"Automatic-Flight-Control-(AEN-422)",label:"Automatic Flight Control (AEN 422)"},
    {value:"Elements-Of-Aerodynamics-(AEN-102)",label:"Elements Of Aerodynamics (AEN 102)"},
    {value:"Space-Dynamics-(AEN-305)",label:"Space Dynamics (AEN 305)"},
    {value:"Vibrations-And-Aeroelasticity-(AEN-301)",label:"Vibrations And Aeroelasticity (AEN 301)"},
    {value:"Aircraft-Structures-(AEN-204)",label:"Aircraft Structures (AEN 204)"},
    {value:"Aerospace-Engineering-Others",label:"Aerospace Engineering Others"}
];

export const fields = [{value:'Computer Science', label:'Computer Science'}, 
    {value:'Electrical Engineering', label:'Electrical Engineering'}, 
    {value:'Electronics and Communiaction',label:'Electronics and Communiaction' }, 
    {value:'Mechanical Engineering', label:'Mechanical Engineering' }, 
    {value:'Aerospace Engineering', label:'Aerospace Engineering'}, 
    {value:'Civil Engineering', label:'Civil Engineering'},
    {value:'Production Engineering', label:'Production Engineering'},
    {value:'Metallurgy Engineering', label:'Metallurgy Engineering'}
];


export const toolbarOptions = [
    [{ 'font': [] }, { 'header': [1, 2, 3, 4, 5, 6, false] }],
    ['bold', 'italic', 'underline','strike', { 'color': [] }, { 'background': [] }],
    ['blockquote','code-block',{ 'script': 'sub'}, { 'script': 'super' }], 
    [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'},{ 'align': [] }],
    ['link', 'image', 'video'],
    ['clean']
];
    
export const formats = [
    'font', 'header', 'bold', 'italic', 'underline', 'strike', 'blockquote',
    'code-block', 'script', 'color','background', 'list', 'bullet', 'indent',
    'link', 'image', 'video', 'align', 'clean'
];
    